# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: communication.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63ommunication.proto\"X\n\x05Piece\x12\x1a\n\x05\x63olor\x18\x01 \x01(\x0e\x32\x0b.PieceColor\x12\x12\n\nidentifier\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x05\x12\x10\n\x08location\x18\x04 \x01(\x05\"F\n\x06Square\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nisOccupied\x18\x02 \x01(\x08\x12\x1c\n\x0c\x63urrentPiece\x18\x03 \x01(\x0b\x32\x06.Piece\"f\n\x05\x42oard\x12$\n\x07squares\x18\x01 \x03(\x0b\x32\x13.Board.SquaresEntry\x1a\x37\n\x0cSquaresEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x16\n\x05value\x18\x02 \x01(\x0b\x32\x07.Square:\x02\x38\x01*\"\n\nPieceColor\x12\t\n\x05WHITE\x10\x00\x12\t\n\x05\x42LACK\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'communication_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOARD_SQUARESENTRY._options = None
  _BOARD_SQUARESENTRY._serialized_options = b'8\001'
  _PIECECOLOR._serialized_start=289
  _PIECECOLOR._serialized_end=323
  _PIECE._serialized_start=23
  _PIECE._serialized_end=111
  _SQUARE._serialized_start=113
  _SQUARE._serialized_end=183
  _BOARD._serialized_start=185
  _BOARD._serialized_end=287
  _BOARD_SQUARESENTRY._serialized_start=232
  _BOARD_SQUARESENTRY._serialized_end=287
# @@protoc_insertion_point(module_scope)
